project 'PixelCityApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PixelCityApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PixelCityApp
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'

end
